version: '3'
services:
  drupal:
    image: drupal:8-apache
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.mysite.localhost'
    expose:
      - 80
    volumes:
      - ./:/opt/drupal
    restart: always

  zoo1:
    image: zookeeper:3.6
    container_name: mysite-zoo1
    hostname: mysite-zoo1
    restart: always
    expose:
      - 2181
      - 7000
    environment:
      # The pre-trained OpenNLP models require a much bigger buffer.
      JVMFLAGS: -Djute.maxbuffer=50000000
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=mysite-zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok
      ZOO_CFG_EXTRA: "metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider metricsProvider.httpPort=7000 metricsProvider.exportJvmInfo=true"
    volumes:
      - .:/mnt/config
volumes:
  solr1:
